### ISSUE TITLE
Undefined method `empty?` for nil:NilClass when running route specs

### ISSUE THREAD

**Issue by danascheider** [danascheider/canto#60]
This is a bug with either the test suite or RSpec itself. I have tested this functionality in the development and test environments using cURL and it works as intended. 

This issue pertains to this code (defined in `canto.rb`):
<pre><code>class Canto &lt; Sinatra::Base
  before do 
    request.body.rewind # best practices
    @request_body = parse_json(request.body.read)
    @id = request.path_info.match(/\d+/).to_s
  end
  post '/users' do
    validate_standard_create # defined in AuthorizationHelper
    User.create(@request_body) ? 201 : 422
  end
end</code></pre>

This, in turn, calls this method from the AuthorizationHelper:
<pre><code>module AuthorizationHelper
  def validate_standard_create
    @request_body.try(:has_key?, :admin) ? access_denied : return
  end
end</code></pre>
However, when I run `/spec/routes/user_routes_spec.rb`, I get failing examples of normal (non-admin-setting) POST requests:
<pre><code>describe 'POST' do 
  let(:path) { '/users' }
  let(:valid_attributes) { { email: 'user@example.com', username: 'justine7', password: 'validpassword666' }.to_json }

  context 'with valid attributes' do 
    it 'returns status 201' do 
      make_request('POST', path, valid_attributes)
      expect(response_status).to eql 201
    end
  end
end</code></pre>

Running this example gets the following error:
<pre><code>  1) Canto POST with valid attributes returns status 201
     Failure/Error: make_request('POST', path, valid_attributes)
     NoMethodError:
       undefined method `empty?' for nil:NilClass
     # ./canto.rb:52:in `block in &lt;class:Canto&gt;'
     # ./features/support/helpers.rb:38:in `make_request'
     # ./spec/routes/user_routes_spec.rb:22:in `block (4 levels) in &lt;top (required)>\&gt;'</code></pre></code>

I am not sure at what point `#empty?` is being called on `nil`; the only place that method appears in my project directory is on a list of Sequel::Model class methods (not in version control). I have traced the problem to Sequel::Model's `initialize_set` method, which takes a hash as an argument and calls `empty?` on the hash. This, in turn, is called from `Sequel::Model.initialize`, which takes a `values` hash and passes it through to `initialize_set`. 

This makes sense, because in the past, Canto has failed to recognize request bodies sent from RSpec through Rack::Test::Methods (although it does recognize request bodies sent through Rack::Test::Methods from Cucumber). It seems the `@request_body` variable is being assigned as `nil` and passed to the model's `create` method.

**Comment by danascheider** [comment]
This has also not be a problem for a while, and since the app has been substantially rewritten since the last time I commented on this issue, I am closing it now.

**Comment by danascheider** [comment]
The problem with this ended up being that a route had a return value that was not properly serialized. In this case (which happened in production), the relevant code looked something like this:
<pre><code>post '/some_route' do 
  request_body.each do |obj|
    Task.create(obj)
  end
end</code></pre>
In this case, the `each` block produced some or other output that was not suitable to be included as a response and consequently raised an error. It was fixed by doing this:
<pre><code>post '/some_route' do 
  request_body.each {|obj| Task.create(obj) }
  [204]
end</code></pre>
